//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ATM.Library.ATMServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATMServer.IATMServer")]
    public interface IATMServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/ValidateCard", ReplyAction="http://tempuri.org/IATMServer/ValidateCardResponse")]
        bool ValidateCard(string BIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/ValidateCard", ReplyAction="http://tempuri.org/IATMServer/ValidateCardResponse")]
        System.Threading.Tasks.Task<bool> ValidateCardAsync(string BIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/AuthorizeCard", ReplyAction="http://tempuri.org/IATMServer/AuthorizeCardResponse")]
        bool AuthorizeCard(string BIN, int pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/AuthorizeCard", ReplyAction="http://tempuri.org/IATMServer/AuthorizeCardResponse")]
        System.Threading.Tasks.Task<bool> AuthorizeCardAsync(string BIN, int pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/ChangePIN", ReplyAction="http://tempuri.org/IATMServer/ChangePINResponse")]
        bool ChangePIN(string BIN, int pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/ChangePIN", ReplyAction="http://tempuri.org/IATMServer/ChangePINResponse")]
        System.Threading.Tasks.Task<bool> ChangePINAsync(string BIN, int pin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IATMServerChannel : E_ATM.Library.ATMServer.IATMServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATMServerClient : System.ServiceModel.ClientBase<E_ATM.Library.ATMServer.IATMServer>, E_ATM.Library.ATMServer.IATMServer {
        
        public ATMServerClient() {
        }
        
        public ATMServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATMServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateCard(string BIN) {
            return base.Channel.ValidateCard(BIN);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCardAsync(string BIN) {
            return base.Channel.ValidateCardAsync(BIN);
        }
        
        public bool AuthorizeCard(string BIN, int pin) {
            return base.Channel.AuthorizeCard(BIN, pin);
        }
        
        public System.Threading.Tasks.Task<bool> AuthorizeCardAsync(string BIN, int pin) {
            return base.Channel.AuthorizeCardAsync(BIN, pin);
        }
        
        public bool ChangePIN(string BIN, int pin) {
            return base.Channel.ChangePIN(BIN, pin);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePINAsync(string BIN, int pin) {
            return base.Channel.ChangePINAsync(BIN, pin);
        }
    }
}
