//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ATM.Library.ATMServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATMServer.IATMServer")]
    public interface IATMServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/DoWork", ReplyAction="http://tempuri.org/IATMServer/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/DoWork", ReplyAction="http://tempuri.org/IATMServer/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/ValidateCard", ReplyAction="http://tempuri.org/IATMServer/ValidateCardResponse")]
        bool ValidateCard(string card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMServer/ValidateCard", ReplyAction="http://tempuri.org/IATMServer/ValidateCardResponse")]
        System.Threading.Tasks.Task<bool> ValidateCardAsync(string card);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IATMServerChannel : E_ATM.Library.ATMServer.IATMServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATMServerClient : System.ServiceModel.ClientBase<E_ATM.Library.ATMServer.IATMServer>, E_ATM.Library.ATMServer.IATMServer {
        
        public ATMServerClient() {
        }
        
        public ATMServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATMServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool ValidateCard(string card) {
            return base.Channel.ValidateCard(card);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCardAsync(string card) {
            return base.Channel.ValidateCardAsync(card);
        }
    }
}
